import mongoose, { Schema } from 'mongoose';
import { IUserSchema } from '@dev-hub-monitor/types';

const userSchema: Schema = new Schema({
  email: { type: String, required: true },
  password: { type: String, required: true },
  githubToken: { type: String },
  verificationToken: { type: String },
  verificationTokenExpiresAt: { type: Date },
  isVerified: { type: Boolean, default: false },
  refreshToken: { type: String },
  gitHubRepoData: { type: Schema.Types.Mixed },
});

const UserModel = mongoose.model<IUserSchema & Document>('DB', userSchema);

export default UserModel;
// type: {
//       id: { type: Number },
//       node_id: { type: String },
//       name: { type: String },
//       full_name: { type: String },
//       private: { type: Boolean },
//       owner: {
//         login: { type: String },
//         id: { type: Number },
//         node_id: { type: String },
//         avatar_url: { type: String },
//       },
//       html_url: { type: String },
//       description: { type: String },
//       fork: { type: Boolean },
//       url: { type: String },
//       created_at: { type: String },
//       updated_at: { type: String },
//       pushed_at: { type: String },
//       git_url: { type: String },
//       ssh_url: { type: String },
//       clone_url: { type: String },
//       svn_url: { type: String },
//       size: { type: Number },
//       stargazers_count: { type: Number },
//       watchers_count: { type: Number },
//       language: { type: String },
//       has_issues: { type: Boolean },
//       has_projects: { type: Boolean },
//       has_downloads: { type: Boolean },
//       has_wiki: { type: Boolean },
//       has_pages: { type: Boolean },
//       forks_count: { type: Number },
//       archived: { type: Boolean },
//       disabled: { type: Boolean },
//       open_issues_count: { type: Number },
//       license: { type: Schema.Types.Mixed },
//       allow_forking: { type: Boolean },
//       is_template: { type: Boolean },
//       web_commit_signoff_required: { type: Boolean },
//       topics: { type: [String] },
//       visibility: { type: String },
//       forks: { type: Number },
//       open_issues: { type: Number },
//       watchers: { type: Number },
//       default_branch: { type: String },
//       permissions: {
//         admin: { type: Boolean },
//         maintain: { type: Boolean },
//         push: { type: Boolean },
//         triage: { type: Boolean },
//         pull: { type: Boolean },
//       },
//     },
